/*
 * SPDX-FileCopyrightText: Copyright (c) 2023-2026 Yegor Bugayenko
 * SPDX-License-Identifier: MIT
 */
package com.yegor256.farea;

import com.jcabi.log.Logger;
import java.io.File;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Comparator;
import java.util.HashSet;
import java.util.Set;
import java.util.stream.Collectors;
import java.util.stream.Stream;
import java.util.zip.ZipEntry;
import java.util.zip.ZipOutputStream;
import org.xembly.Directives;

/**
 * This classpath classes packaged as a plugin.
 *
 * @since 0.0.1
 */
final class Itself {

    /**
     * Directory of Maven project.
     */
    private final Path home;

    /**
     * Original POM, of the current project.
     */
    private final Base base;

    /**
     * The classpath string, separated by {@code File.pathSeparator}.
     */
    private final String classpath;

    /**
     * Should it fail if plugin.xml is not in the classpath?
     */
    private final boolean careful;

    /**
     * Ctor.
     * @param dir The directory of the Maven project
     */
    Itself(final Path dir) {
        this(dir, new Base());
    }

    /**
     * Ctor.
     * @param dir The directory of the Maven project
     * @param pom Original pom.xml
     */
    Itself(final Path dir, final Base pom) {
        this(dir, pom, true);
    }

    /**
     * Ctor.
     * @param dir The directory of the Maven project
     * @param pom Original pom.xml
     * @param crf Careful?
     */
    Itself(final Path dir, final Base pom, final boolean crf) {
        this(dir, pom, crf, System.getProperty("java.class.path"));
    }

    /**
     * Ctor.
     * @param dir The directory of the Maven project
     * @param pom Original pom.xml
     * @param crf Careful?
     * @param cpath The classpath
     * @checkstyle ParameterNumberCheck (5 lines)
     */
    Itself(final Path dir, final Base pom, final boolean crf, final String cpath) {
        this.home = dir;
        this.base = pom;
        this.careful = crf;
        this.classpath = cpath;
    }

    /**
     * Deploy it to local Maven repository.
     * @param local Path of local Maven repo, usually "~/.m2/repository"
     * @return The {@code version} of a new Maven dependency just deployed
     * @throws IOException If fails
     */
    public String deploy(final Path local) throws IOException {
        final String version = this.next();
        final Path place = local.resolve(
            String.format(
                "%s/%s/%s",
                this.base.groupId().replace(".", "/"),
                this.base.artifactId(), version
            )
        );
        final String name = String.format(
            "%s-%s", this.base.artifactId(), version
        );
        synchronized (Itself.class) {
            this.assembleJar(
                version,
                place.resolve(
                    String.format("%s.jar", name)
                )
            );
            Files.write(
                place.resolve(
                    String.format("%s.pom", name)
                ),
                this.base.xml().toString().getBytes(StandardCharsets.UTF_8)
            );
        }
        return version;
    }

    /**
     * Zip the entire module into a JAR.
     * @param version Version of the JAR to use
     * @param zip The location of the JAR
     * @throws IOException If fails
     */
    private void assembleJar(final String version, final Path zip) throws IOException {
        if (zip.toFile().exists()) {
            Files.delete(zip);
        }
        if (zip.toFile().getParentFile().mkdirs()) {
            Logger.debug(
                this, "Directory created at %[file]s",
                zip.toFile().getParentFile()
            );
        }
        Files.createFile(zip);
        final Set<String> seen = new HashSet<>(0);
        final String[] jars = this.classpath.split(File.pathSeparator);
        if (!this.zip(version, zip, seen, jars) && this.careful) {
            throw new IllegalStateException(
                String.join(
                    " ",
                    "There is no 'META-INF/maven/plugin.xml' file in the classpath.",
                    "Most probably you haven't configured maven-plugin-plugin",
                    "or the 'packaging' of your Maven project is not set to 'maven-plugin'.",
                    "Normally, the 'plugin.xml' file is in the 'target/' directory.",
                    "This error may also be caused by the fact that you haven't",
                    "executed the full Maven build, but only running a test.",
                    "The 'plugin.xml' file is generated by the 'maven-plugin-plugin'",
                    "plugin right before the execution of unit tests."
                )
            );
        }
        Logger.debug(
            Itself.class,
            "JAR saved to %[file]s (%[size]s, %d files, %d jars)",
            zip, zip.toFile().length(), seen.size(), jars.length
        );
    }

    /**
     * Package it in a single ZIP.
     * @param version Version of the JAR to use
     * @param zip The ZIP file to create
     * @param seen List of entries seen already
     * @param jars JARs to package into the ZIP (including the "target/classes/" directory)
     * @return TRUE if descriptor is found (has "plugin.xml" file inside)
     * @throws IOException If fails
     * @checkstyle ParameterNumberCheck (10 lines)
     */
    @SuppressWarnings("PMD.CognitiveComplexity")
    private boolean zip(final String version, final Path zip, final Set<String> seen,
        final String... jars) throws IOException {
        boolean descripted = false;
        try (ZipOutputStream stream = new ZipOutputStream(Files.newOutputStream(zip))) {
            for (final String path : jars) {
                final File jar = new File(path);
                if (!jar.isDirectory()) {
                    continue;
                }
                final Path src = jar.toPath();
                for (final Path file : Files.walk(src).collect(Collectors.toList())) {
                    if (file.toFile().isDirectory()) {
                        continue;
                    }
                    final String name = src.relativize(file).toString().replace("\\", "/");
                    if (seen.contains(name)) {
                        continue;
                    }
                    final ZipEntry entry = new ZipEntry(name);
                    stream.putNextEntry(entry);
                    if ("META-INF/maven/plugin.xml".equals(name)) {
                        this.copyDescriptor(file, version, stream);
                        descripted = true;
                    } else {
                        Files.copy(file, stream);
                    }
                    stream.closeEntry();
                    seen.add(name);
                }
            }
            if (!descripted) {
                final String pname = "target/plugin.xml";
                final Path dup = this.home.resolve(pname);
                if (dup.toFile().exists()) {
                    final ZipEntry entry = new ZipEntry(pname);
                    stream.putNextEntry(entry);
                    this.copyDescriptor(dup, version, stream);
                    stream.closeEntry();
                    Logger.debug(Itself.class, "The %[file]s copied into the JAR", dup);
                }
            }
        }
        return descripted;
    }

    /**
     * Copy "plugin.xml" into the ZIP.
     * @param file Location of the "plugin.xml"
     * @param version The version of itself
     * @param stream The ZIP
     * @throws IOException If fails
     */
    private void copyDescriptor(final Path file, final String version,
        final ZipOutputStream stream) throws IOException {
        final Path descriptor = this.temp(version).resolve("plugin.xml");
        Files.copy(file, descriptor);
        new Pom(descriptor).modify(
            new Directives()
                .xpath("/plugin/version")
                .strict(1)
                .set(version)
        );
        Files.copy(descriptor, stream);
    }

    /**
     * Create new version.
     * @return The version
     * @throws IOException If fails
     */
    private String next() throws IOException {
        while (true) {
            final String version = String.format(
                "%s-farea-%08x", this.base.version(), System.nanoTime()
            );
            synchronized (Itself.class) {
                final Path temp = this.temp(version);
                if (temp.toFile().mkdirs()) {
                    Runtime.getRuntime().addShutdownHook(
                        new Thread(
                            () -> {
                                if (temp.toFile().exists()) {
                                    try (Stream<Path> files = Files.walk(temp)) {
                                        files
                                            .map(Path::toFile)
                                            .sorted(Comparator.reverseOrder())
                                            .forEach(File::delete);
                                    } catch (final IOException ex) {
                                        throw new IllegalArgumentException(ex);
                                    }
                                }
                            }
                        )
                    );
                    return version;
                }
            }
        }
    }

    /**
     * Make a temp directory for this version.
     * @param version The version
     * @return The path
     */
    private Path temp(final String version) {
        return this.home
            .resolve("target")
            .resolve("farea")
            .resolve(version);
    }

}
